name: Build Docker Image
description: "Build a service Docker image with GHA cache. Optionally push to GHCR."

inputs:
  service:
    description: "Service directory name (e.g. claude-agent)"
    required: true
  push:
    description: "Whether to push the image to GHCR"
    required: false
    default: "true"
  registry:
    description: "Container registry"
    required: false
    default: "ghcr.io"
  token:
    description: "GitHub token for GHCR login"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      if: ${{ inputs.push == 'true' }}
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.service }}
        tags: |
          type=sha,prefix=
          type=raw,value=latest

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./${{ inputs.service }}
        push: ${{ inputs.push }}
        load: ${{ inputs.push != 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha,scope=${{ inputs.service }}
        cache-to: type=gha,mode=max,scope=${{ inputs.service }}
