name: Build Export Handler Image

on:
  push:
    branches: [main]
    paths:
      - "export-handler/**"
      - ".github/workflows/build-export-handler.yaml"
  pull_request:
    branches: [main]
    paths:
      - "export-handler/**"
      - ".github/workflows/build-export-handler.yaml"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build-image.yaml
    with:
      service: export-handler
