name: Build Router Image

on:
  push:
    branches: [main]
    paths:
      - "router/**"
      - ".github/workflows/build-router.yaml"
  pull_request:
    branches: [main]
    paths:
      - "router/**"
      - ".github/workflows/build-router.yaml"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build-image.yaml
    with:
      service: router
